### ISSUE TITLE
Panic on trying to check fyne

### ISSUE THREAD

**Issue by Jacalz** [orijtech/tickeryzer#6]
I just got it using `go get` on my Linux computer (with Go 1.15) and tried to run it like `tickeryzer ./...` within the main folder of [fyne](https://github.com/fyne-io/fyne) and received this panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6b9673]

goroutine 5374 [running]:
github.com/orijtech/tickeryzer.run.func1(0x7a3780, 0xc030b45d00, 0x1, 0xc00081ce00, 0x5, 0x20, 0x1)
	/home/jacob/go/src/github.com/orijtech/tickeryzer/tickeryzer.go:93 +0x293
golang.org/x/tools/go/ast/inspector.(*Inspector).WithStack(0xc035a9caa0, 0xc000eb6b30, 0x1, 0x1, 0xc000eb6b20)
	/home/jacob/go/src/golang.org/x/tools/go/ast/inspector/inspector.go:126 +0x142
github.com/orijtech/tickeryzer.run(0xc02a250f70, 0xc02a250f70, 0x0, 0x0, 0x0)
	/home/jacob/go/src/github.com/orijtech/tickeryzer/tickeryzer.go:55 +0x112
golang.org/x/tools/go/analysis/internal/checker.(*action).execOnce(0xc0368ddcc0)
	/home/jacob/go/src/golang.org/x/tools/go/analysis/internal/checker/checker.go:691 +0x8b9
sync.(*Once).doSlow(0xc0368ddcc0, 0xc0013c3f90)
	/usr/lib64/golang/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/lib64/golang/src/sync/once.go:57
golang.org/x/tools/go/analysis/internal/checker.(*action).exec(0xc0368ddcc0)
	/home/jacob/go/src/golang.org/x/tools/go/analysis/internal/checker/checker.go:579 +0x65
golang.org/x/tools/go/analysis/internal/checker.execAll.func1(0xc0368ddcc0)
	/home/jacob/go/src/golang.org/x/tools/go/analysis/internal/checker/checker.go:567 +0x34
created by golang.org/x/tools/go/analysis/internal/checker.execAll
	/home/jacob/go/src/golang.org/x/tools/go/analysis/internal/checker/checker.go:573 +0x125
```

**Comment by cuonglm** [comment]
@Jacalz Thanks for reporting. This is now fixed in main.
